FROM maven:3.6.0-jdk-11-slim AS build
WORKDIR /conversor
COPY src /conversor/src
COPY pom.xml /conversor
RUN mvn -f /conversor/pom.xml clean package -DskipTests

FROM openjdk:11-jre-slim
COPY --from=build /conversor/target/conversor-1.0-SNAPSHOT.jar /usr/local/lib/conversor.jar
ENTRYPOINT ["java", "-jar", "/usr/local/lib/conversor.jar"]